### ISSUE TITLE
Hinweis für "kaufen"-Button umbenennen

### ISSUE THREAD

**Issue by Toflar** [isotope/docs#16]

**Comment by netzarbeiter** [comment]
Nach der Lektüre von http://de.wikipedia.org/wiki/Button-L%C3%B6sung#Zul.C3.A4ssige_Bezeichnungen haben Andy und ich die Bezeichnung auf Transifex in "Kostenpflichtig bestellen" geändert.

**Comment by Toflar** [comment]
Sehr gut. Wollen wir trotzdem einen Hint einfügen? Falls jemand eben lieber "bestellen" hätte? :)

**Comment by netzarbeiter** [comment]
Kannst du es bitte noch in die 2.3 übertragen? https://isotopeecommerce.org/de/handbuch/v/2.2/r/tipps-und-tricks.html

**Comment by Toflar** [comment]
Erledigt, danke!
