### ISSUE TITLE
Translations in products

### ISSUE THREAD

**Issue by alexisrosique** [isotope/docs#17]
Hi!
Congratulations for this ecommerce it is simply and easy to work. I have a question, I'm using the Demo of isotope to try all odds, the articles by default are written in Deutsch. I would like know how this articles are translated. I'm working in shop multi language, Default language is Spanish and secondary language is English. 
Thanks you and congratulations.

**Comment by netzarbeiter** [comment]
For your information there is a [bug](https://github.com/isotope/core/issues/1424) with the language selector in the newest demo version (Isotope eCommerce 2.3 beta1).

It works fine with [Isotope eCommerce 2.2](https://isotopeecommerce.org/files/demo/isotope_demo_2.2.3.tar.gz).

The place were you can get further help concerning Isotope is the [bulletin board](https://community.contao.org/en/forumdisplay.php?151-isotope).
