### ISSUE TITLE
__MACOSX-Verzeichnisse im Demo-ZIP

### ISSUE THREAD

**Issue by michelbalzer** [isotope/docs#23]
Im aktuellen Demo-Zip (https://isotopeecommerce.org/de/demo.html, Isotope 2.3.4) ist nach dem Entpacken ein Ordner __MACOSX sichtbar. Dieser wird durch die „Archiv erstellen“-Funktion im Finder unter OS X erstellt und mitgepackt. Sieht nicht schön aus und bringt Ballast mit rein.

Lösung: nicht den Finder zum zippen benützen ;) alternativ im Terminal, oder ein anderes Programm/App dafür nutzen.

Ob dies auch im tar.gz. auftritt, kann ich nicht sagen, da ich es nicht geöffnet bekam. Dafür mache ich eventuell ein anderes TIcket auf.

![bildschirmfoto 2016-05-04 um 15 53 17](https://cloud.githubusercontent.com/assets/1337412/15019421/457942b4-121e-11e6-9e5f-7ad7394db664.png)

(via https://twitter.com/ohne_a/status/727858843468828672)

**Comment by netzarbeiter** [comment]
Demo (Isotope eCommerce 2.3.5)
https://isotopeecommerce.org/de/demo.html
