### ISSUE TITLE
Demo verwendet noch Isotope 3.2.4 statt 3.2.5

### ISSUE THREAD

**Issue by michelbalzer** [isotope/docs#24]
In der Demo wird noch die Version 3.2.4 und nicht 3.2.5 verwendet. Beim Update am besten #23 beachten.

https://isotopeecommerce.org/de/demo.html

**Comment by netzarbeiter** [comment]
Demo (Isotope eCommerce 2.3.5)
https://isotopeecommerce.org/de/demo.html
