### ISSUE TITLE
Versandkosten Bestellübersicht/-details 

### ISSUE THREAD

**Issue by laRocca** [isotope/docs#27]
Hallo,
[
im Bezug auf meinen Contao-Post:](https://community.contao.org/de/showthread.php?63016-Versandkosten-Bestell%FCbersicht-details&p=412907)

ich hatte in meinem Shop (Frieden-Berg.de) bisher nur 1 Versandmöglichkeit (DHL VERSAND 9€) – da ist auch alles gut gelaufen.
Jetzt ist eine 2. dazu gekommen (PREMIUM VERSAND 14,90€) und jetzt gibt es Probleme mit der Darstellung der Versandkosten auf der Bestellübersicht und den Bestelldetails:

versandkosten.jpg
![attachment](https://cloud.githubusercontent.com/assets/4539461/16479481/de03f25a-3ea0-11e6-9b49-d9ea1b41d12b.jpg)

versandkosten2.jpg
![attachment-1](https://cloud.githubusercontent.com/assets/4539461/16479484/e15f3338-3ea0-11e6-82cd-a4f4eb2674ca.jpg)

Ich weiß nicht genau nach was ich in den Templates schauen muss, damit ich diese umpositionieren kann. Kann mir da jemand helfen?

**Comment by Toflar** [comment]
Der Issue-Tracker ist für Bug-Reports. Für Fragen und Support ist das Community Forum der richtige Ort. Professional Support gibt's [im Circle](https://isotopeecommerce.org/de/circle.html).
